# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - deploy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.ACCESS_KEY }}
          host: ${{ secrets.HOSY }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd tscenping
            git reset --hard
            git fetch
            git pull
            npm i
            npm run build
