# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - deploy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Generate Environment
        run: |
         echo "REACT_APP_REDIRECTION_URL_42=${{ secrets.REACT_APP_REDIRECTION_URL_42 }}" >> .env
         echo "REACT_APP_DEFAULT_PROFILE=${{ secrets.REACT_APP_DEFAULT_PROFILE }}" >> .env
         echo "REACT_APP_REDIRECTION_URL_GOOGLE=${{ secrets.REACT_APP_REDIRECTION_URL_GOOGLE }}" >> .env
         echo "REACT_APP_PUBLIC_ENDPOINT=${{ secrets.REACT_APP_PUBLIC_ENDPOINT }}" >> .env
         echo "REACT_APP_BASEURL=${{ secrets.REACT_APP_BASEURL }}" >> .env
         echo "REACT_APP_SOCKET_CHANNELS=${{ secrets.REACT_APP_SOCKET_CHANNELS }}" >> .env
         echo "REACT_APP_SOCKET_GAMES=${{ secrets.REACT_APP_SOCKET_GAMES }}" >> .env
         echo "REACT_APP_S3_ACCESS_KEY=${{ secrets.REACT_APP_S3_ACCESS_KEY }}" >> .env
         echo "REACT_APP_S3_SECRET_KEY=${{ secrets.REACT_APP_S3_SECRET_KEY }}" >> .env
         echo "REACT_APP_S3_REGION=${{ secrets.REACT_APP_S3_REGION }}" >> .env
         echo "REACT_APP_S3_BUCKET_NAME=${{ secrets.REACT_APP_S3_BUCKET_NAME }}" >> .env
         echo "REACT_APP_FIREBASE_ID=${{ secrets.REACT_APP_FIREBASE_ID }}" >> .env
         
        
      - name: Build
        run: npm run build
        
      - name:  Aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: aws s3 sync --region ap-northeast-2 build s3://tscenping-fe --delete
        working-directory:  ./
        
      - name: CloudFront Invalidate Cache
        run: aws cloudfront --region ap-northeast-2 create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
